---
deployment:
  tasks:
    - export APPPATH=/home/qamarislines/qamarisshippinglines.com
    - cd $APPPATH && npm ci
    - cd $APPPATH && npm run build
    - mkdir -p $APPPATH/tmp
    - touch $APPPATH/tmp/restart.txt