---
deployment:
  tasks:
    - export APPPATH=/home/qamarislines/qamarisshippinglines.com
    - /bin/cp -a . $APPPATH
    - cd $APPPATH && npm ci
    - cd $APPPATH && npm run build
    - touch $APPPATH/tmp/restart.txt